# Uncomment this line to define a global platform for your project
  platform :ios, '7.0'

target 'TWGeoCounty' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TWGeoCounty
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps', '~> 1.13.1'
end
